#!/usr/bin/env python3

#run from within directory with .json files to combine
# ./combine output_file-name.json

import os
import json
import sys
from pathlib import Path


if len(sys.argv) < 2:
    print("Usage: combine <output_file_name>")
    sys.exit(1)
output_file_name = sys.argv[1]


current_dir = Path.cwd()

dataset = []

# only .json files
for file_path in current_dir.glob("*.json"):
    with open(file_path, 'r') as f:
        file_data = json.load(f)
        if isinstance(file_data, list):
            dataset.extend(file_data)
        else:
            dataset.append(file_data)


print(f"Combined dataset contains {len(dataset)} samples.")


with open(output_file_name, "w") as outfile:
    json.dump(dataset, outfile, indent=2)

print(f"Combined dataset saved as {output_file_name}")
